title: MyDad.Is
description: Short Stories about Our Fathers

url: http://mydad.is
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: joeykirk
   twitter: joeykirk
   facebook: joeykirk
   email: joey.kirk@gmail.com

google_analytics: 
